name: elephant_analysis_env
channels:
  - conda-forge
dependencies:
  - python=3.11.5
  - jupyterlab=3.6.3
  - numpy=1.24.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scipy=1.11.1
  - pandas=2.0.3
  - umap-learn=0.5.5
  - opentsne=1.0.1
  - scikit-learn=1.3.0
  - anndata=0.10.3
  - scanpy=1.9.6
  - colorcet=3.0.1
  - pip=23.3.1
